blog/urls.py
from django.urls import path
from .views import post_list, post_detail, post_share, post_comment, post_search

app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post-list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',post_detail, name='post-detail'),
    path('<int:post_id>/share/',post_share,name='post-share'),
    path('<int:post_id>/comment/',post_comment,name='post-comment'),
    path('tag/<slug:tag_slug>/',post_list, name='post_list_by_tag'),
    path('search/',post_search, name='post-search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from wsgiref.validate import validator
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
from django.utils.translation.template import blankout
from django.core.exceptions import ValidationError
from taggit.managers import TaggableManager

def validate_video_file_size(value):
    max_size = 10 * 1024 * 1024  # Maksimal hajm: 10 MB
    if value.size > max_size:
        raise ValidationError(f'Video hajmi 10 MB dan oshmasligi kerak. Siz yuklagan hajm: {value.size / (1024 * 1024):.2f} MB')

def validate_video_file(value):
    valid_mime_types = ['video/mp4', 'video/avi', 'video/mov']
    file_mime_type = value.file.content_type
    if file_mime_type not in valid_mime_types:
        raise ValidationError('Faqat MP4, AVI yoki MOV formatidagi video fayllar qabul qilinadi.')

def validate_image_file_size(value):
    max_size = 5 * 1024 * 1024  # Maksimal hajm: 5 MB
    if value.size > max_size:
        raise ValidationError(f'Rasm hajmi 5 MB dan oshmasligi kerak. Siz yuklagan hajm: {value.size / (1024 * 1024):.2f} MB')

def validate_image_file_type(value):
    valid_mime_types = ['image/jpeg', 'image/png', 'image/gif']  # Ruxsat etilgan MIME turlari
    file_mime_type = value.file.content_type
    if file_mime_type not in valid_mime_types:
        raise ValidationError('Faqat JPEG, PNG yoki GIF formatidagi rasm fayllarini yuklash mumkin.')


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=PostModel.Status.PUBLISHED)


class PostModel(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    image = models.ImageField(upload_to="images/",blank=True, null=True)
    video = models.FileField(upload_to="videos/",blank=True, null=True,validators=[validate_video_file_size,validate_video_file])
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        get_latest_by = 'publish'
        db_table = 'Posts'
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


class CommentModel(models.Model):
    post = models.ForeignKey(PostModel,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/views.py
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from pyexpat.errors import messages
from .froms import EmailPostForm, CommentForm, SearchForm
from .models import PostModel, CommentModel
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.conf import settings
from django.views.decorators.http import require_POST
from taggit.models import Tag


# def post_list(request):
#     post_list = PostModel.published.all()
#     paginator = Paginator(post_list, 5)
#     page = request.GET.get('page',1)
#     posts = paginator.get_page(page)
#     return render(request, 'blog/post/post_list.html', {'posts': posts})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(PostModel,
                             status=PostModel.Status.PUBLISHED,
                             slug=slug,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)
    form = CommentForm()

    poat_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = PostModel.published.filter(tags__in=poat_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})


def post_list(request, tag_slug=None):
    post_list = PostModel.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/post_list.html',
                  {'posts': posts,
                   'tag': tag})


# class PostListView(ListView):
#     model = PostModel
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/post_list.html'
#
#     def get_queryset(self):
#         return PostModel.published.all()
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['is_paginated'] = True
#         return context


# class PostDetailView(DetailView):
#     model = PostModel
#     context_object_name = 'post'
#     template_name = 'blog/post/detail.html'
#
#     def get_queryset(self):
#         return PostModel.published.all()
#
#     def get_object(self, queryset=None):
#         slug = self.kwargs.get('slug')
#         return get_object_or_404(self.get_queryset(), slug=slug)


def post_share(request, post_id):
    post = get_object_or_404(PostModel, pk=post_id, status=PostModel.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']}   {post.title}"
            message = f"Read {post.title}  at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(PostModel, pk=post_id, status=PostModel.Status.PUBLISHED)
    comment = None

    form = CommentForm(data=request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = PostModel.published.annotate(
                search=SearchVector('title', 'body')
            ).filter(search=query)

    return render(request,'blog/post/search.html',{'form' : form, 'query' : query,'results':results})

templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body }}
<p>
    <a href="{% url 'blog:post-share' post.id %}">
    Share this post
    </a>
</p>

<div>
{% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" width="400" height="300">
{% endif %}
</div>


<div>{% if post.video %}
<video width="400" height="300" controls>
    <source src="{{ post.video.url }}">
    Sizning brauzeringiz videoni qo'llab-quvvatlamaydi.
</video>
{% endif %}
</div>

<h2>Yaqin postlar</h2> <br>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
Hozircha yaqin postlar yo'q!
{% endfor %}

{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>Hozircha kommentlar yo'q!!!</p>
{% endfor %}
{% include "blog/post/includes/comment_form.html" %}
{% endblock %}

templates/blog/post/latest_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> <br>
    </li>
  {% endfor %}
 </ul>
</body>
</html>

templates/blog/post/post_list.html
{% extends "blog/base.html" %}
{% load blog_tags %}


{% block content %}
<h1 style="text-align: center">Mening Blogim</h1>
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>

    <br>

<div>
{% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" width="400" height="300">
{% endif %}
</div>


<div>{% if post.video %}
<video width="400" height="300" controls>
    <source src="{{ post.video.url }}">
    Sizning brauzeringiz videoni qo'llab-quvvatlamaydi.
</video>
{% endif %}
</div>

<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
        {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|truncatewords_html:30 }}
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for post in results %}
<h4>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h4>
{{ post.body|truncatewords_html:12 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url 'blog:post-search' %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    <b>"{{ post.title }}"</b>   <b>{{ form.cleaned_data.to }}</b> ga muvaffaqiyatli yuborildi.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post" novalidate>
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}